name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Rename PDF
        run: mv main.pdf public/main.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: public/main.pdf
      - name: Publish PDF to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'public/main.pdf'
          commit_message: Rebuilt PDF
     
